version: '2'
services:

    §§INSTANCE-stategraems:
      build: 
          context: ./images/stategraem
      image: bibbox/stategraems
      container_name: §§INSTANCE-stategraems
      links:
        - §§INSTANCE-stategraems-mysql:stategraems-db
      depends_on:
        - §§INSTANCE-stategraems-db
      volumes_from:
        - §§INSTANCE-stategraems-data
      ports:
        - "§§PORT:8080"

    §§INSTANCE-stategraems-db:
      image: mysql
      container_name: §§INSTANCE-stategraems-db
      environment:
        - MYSQL_ROOT_PASSWORD=§§MYSQL_ROOT_PASSWORD
      depends_on:
        - §§INSTANCE-stategraems-data
      volumes_from:
        - §§INSTANCE-stategraems-data

    §§INSTANCE-stategraems-data:
      image: busybox
      container_name: §§INSTANCE-stategraems-data
      volumes:
        - §§FOLDER/var/lib/mysql:/var/lib/mysql
        - §§FOLDER/data:/data

